### ISSUE TITLE
aliyun的oss并不能使用

### ISSUE THREAD

**Issue by sallyciel** [ymm-tech/gods-pen-docker#5]
已测试AK有权限，并且可通过aliyun的oss-browser进行各种权限操作，但是配置到config里面并不生效，邮件模块倒是正常

**Comment by mingyuanwei** [comment]
码良官网服务即是使用阿里云 oss 的
方便的话可以贴一下报错日志或者脱敏 oss 配置截图

**Comment by sallyciel** [comment]
> 码良官网服务即是使用阿里云 oss 的
> 方便的话可以贴一下报错日志或者脱敏 oss 配置截图

我直接把API指向码良官方，难得折腾，哈哈
